import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { NextPage } from 'next'
import { useRouter } from 'next/router'
import Link from 'next/link'

const Home : NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Link href={'./calendarPage'}>GOGO</Link>
          <a onClick={()=>router.push('./calendarPage')}>Go Calendar</a>

        </div>
      </main>
    </>
  )
}

export default Home;
