import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { NextPage } from 'next'
import { useRouter } from 'next/router'
import Link from 'next/link'
import styled from "@emotion/styled/macro";
import tw from "twin.macro";

const StyleDiv = styled.div`
  background: green;
  font-size: 5rem;
`

const Home : NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <StyleDiv>
          <Link href={'./calendarPage'}>GOGO</Link>
          {/* <a onClick={()=>router.push('./calendarPage')}>Go Calendar</a> */}
        </StyleDiv>
      </main>
    </>
  )
}

export default Home;
